### ISSUE TITLE
could you support MP4 test ?

### ISSUE THREAD

**Issue by sankexin** [pkhungurn/talking-head-anime-demo#17]
Linux can't be tested without camera and display interface！！could you support MP4 test ? 

Traceback (most recent call last):
  File "app/manual_poser.py", line 135, in <module>
    root = Tk()
  File "/home/dd/anaconda3/envs/head_anime/lib/python3.8/tkinter/__init__.py", line 2261, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
(head_anime) dd@ubuntu150:~/150/talking-head-anime-demo$ ls app/
__init__.py  manual_poser.py  puppeteer.py
(head_anime) dd@ubuntu150:~/150/talking-head-anime-demo$ python app/puppeteer.py 
[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (887) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
Traceback (most recent call last):
  File "app/puppeteer.py", line 201, in <module>
    master = Tk()
  File "/home/dd/anaconda3/envs/head_anime/lib/python3.8/tkinter/__init__.py", line 2261, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by dragonmeteor** [comment]
manual_poser is a GUI application, so it naturally requires a display. puppeteer is designed to work with a web camera. I will not add more features to the code because they suffice for the demo purpose. If you want additional features, you're welcome to extend the software yourself.
