### ISSUE TITLE
Can we run the 'talking-head-anime-demo' on Linux?

### ISSUE THREAD

**Issue by renmengyuan** [pkhungurn/talking-head-anime-demo#18]
Can we run the 'talking-head-anime-demo' on Linux?

**Comment by dragonmeteor** [comment]
Yes. I've seen people successfully done it.

https://twitter.com/mctktkmc/status/1232269861239156744

**Comment by ayush9198gupta** [comment]
@renmengyuan 

Yes , you can run the code on LInux machine - its working
