### ISSUE TITLE
unsupported operand type(s) for -: 'point' and 'point'

### ISSUE THREAD

**Issue by albbzmkh** [pkhungurn/talking-head-anime-demo#22]
unsupported operand type(s) for -: 'point' and 'point'

**Comment by dragonmeteor** [comment]
Can you give me the whole exception text?

**Comment by DWCTOD** [comment]
I meet the same problem，but it work well in ubuntu 16.04

the error message is

  File "app\puppeteer.py", line 142, in update_image
    left_eye_normalized_ratio = compute_left_eye_normalized_ratio(face_landmarks, eye_min_ratio, eye_max_ratio)
  File "C:\Users\Desktop\talking-head-anime-demo\puppet\util.py", line 15, in compute_left_eye_normalized_ratio
    min_ratio, max_ratio)
  File "C:\Users\Desktop\talking-head-anime-demo\puppet\util.py", line 26, in compute_eye_normalized_ratio
    left_eye_horiz_diff = face_landmarks.part(eye_horiz_points[0]) - face_landmarks.part(eye_horiz_points[1])
TypeError: unsupported operand type(s) for -: 'point' and 'point'

**Comment by DWCTOD** [comment]
> I meet the same problem，but it work well in ubuntu 16.04
> 
> the error message is
> 
> File "app\puppeteer.py", line 142, in update_image
> left_eye_normalized_ratio = compute_left_eye_normalized_ratio(face_landmarks, eye_min_ratio, eye_max_ratio)
> File "C:\Users\Desktop\talking-head-anime-demo\puppet\util.py", line 15, in compute_left_eye_normalized_ratio
> min_ratio, max_ratio)
> File "C:\Users\Desktop\talking-head-anime-demo\puppet\util.py", line 26, in compute_eye_normalized_ratio
> left_eye_horiz_diff = face_landmarks.part(eye_horiz_points[0]) - face_landmarks.part(eye_horiz_points[1])
> TypeError: unsupported operand type(s) for -: 'point' and 'point'

this is because I was use dlib 19.7, not dlib 19.19. When I change it, that's  ok
