### ISSUE TITLE
Is there any open source plan for model training part?

### ISSUE THREAD

**Issue by Gatevin** [pkhungurn/talking-head-anime-demo#23]
Thanks for this outstanding work!

I tried this demo to generate some gif for my favorite waifu images, most of them works well.
But when character doesn't face to front, the model works not well on eye area generation.

Is there any open source plan for model training?  That will be helpful to train model that meets my requirement.

It seems that some new features are created such as iris rotation, is there any plan to share that?

**Comment by dragonmeteor** [comment]
Thank you for your interest in this work.

No. I have no plans to open source the training code. However, all training processes are standard supervised training, it is very easy to code up now that you have access to the model.

I'm currently adding more features, and I plan to release the new model. I'm not so sure when it will be done though.

**Comment by Gatevin** [comment]
Thanks for your quickly reply :)
I read the Network Specification section in the published article and will try to code it.

新しいモデルを楽しみにしています :satisfied:
