### ISSUE TITLE
How to replace the Cuda driver in the AMD Product.

### ISSUE THREAD

**Issue by Kazto-lsk** [pkhungurn/talking-head-anime-demo#27]
Always stay healthy.

I think this project is very positive, But the graphics card I have now is RX580.
Is there any way the AMD product line can do in this project?
If not, what is the best product to use this project?

**Comment by dragonmeteor** [comment]
The short answer is no. It might be possible by porting the network to a more universal format with some other tools, but you'd have to do it by yourself.

The code is best run on a graphics card that supports CUDA. I've personally tested the network on the GeForce GTX 1080 Ti and the Titan RTX.
