### ISSUE TITLE
Is there some ways to save the module as mtn module file

### ISSUE THREAD

**Issue by FzWjScJ** [pkhungurn/talking-head-anime-demo#29]
Hello,I want to put the module on my website.But I found that need a mtn file seems like every action that the model makes.
![image](https://user-images.githubusercontent.com/43847366/108626574-c471ca80-748b-11eb-9187-76545cd20446.png)
So is there any ways to save these action？

**Comment by FzWjScJ** [comment]
or maybe cmo3 file.(forgive me for my poor English. XD

**Comment by dragonmeteor** [comment]
First, this software does not work like Live2D. It uses a neural network to generate a new image from the inputs. There is no underlying movable images that can be extracted and save.

That said, the real answer is "I don't know." You have to figure it out yourself.

**Comment by FzWjScJ** [comment]
okey,Thakns. Let me try.
