### ISSUE TITLE
mouth movement unclear

### ISSUE THREAD

**Issue by onzone** [pkhungurn/talking-head-anime-demo#31]
First of all, Kudos to your amazing work.
For some of the anime character, there is hardly any lip movement when in webcam I am moving my lips. Specially if the character is male. I have generated some character myself. Attaching two examples of avatar image.I have maintained all the criteria you mentioned.  Any suggestions would be very helpful.

![avatar3](https://user-images.githubusercontent.com/7061779/112486409-d94ec000-8da1-11eb-9de0-e47a413e44f9.png)
![avatar4](https://user-images.githubusercontent.com/7061779/112486430-de137400-8da1-11eb-82bd-2a4d30a7173c.png)

**Comment by dragonmeteor** [comment]
This version of the software cannot open closed mouth, so you will not be able to see any mouth movement from the first image.

To get some mouth movement from the second image, paint the mouth red or pink.
