### ISSUE TITLE
How does it work  with existing videos ?

### ISSUE THREAD

**Issue by yslion** [pkhungurn/talking-head-anime-demo#34]
How does it work  with existing videos  ?

**Comment by dragonmeteor** [comment]
The code in this repository does not provide an interface that accepts videos as input, and there's no plan to add that functionality. You have to modify the software to do so yourself.

**Comment by JiliHili** [comment]
./app/puppeteer.py
line 201 video_capture = cv2.VideoCapture('video file path')
