### ISSUE TITLE
Was this project demonstrated on Nvidia GTC 2021?

### ISSUE THREAD

**Issue by edmund-zhao** [pkhungurn/talking-head-anime-demo#37]
Link : ["Youtube"](https://youtu.be/eAn_oiZwUXA)  TimePoint: 15:33

![image](https://user-images.githubusercontent.com/53864204/130362720-fd580150-512e-4bab-81a4-36e1ba6b502c.png)

**Comment by dragonmeteor** [comment]
No. This model cannot do anything like what was demonstrated in the video.
