### ISSUE TITLE
Why it looks terrible if I choose my images to work with this project?

### ISSUE THREAD

**Issue by tanyuzhou** [pkhungurn/talking-head-anime-demo#4]
I have already resize these images(some of them came from [MakeGirls.Moe](https://make.girls.moe/#/)  @makegirlsmoe) to 256x256, their heads in 128x128, and background is transparent. 
Is there any thing I should do?

**Comment by tanyuzhou** [comment]
![lty](https://user-images.githubusercontent.com/59681912/72049395-da5d1400-32f9-11ea-989f-ed3d83d5bb70.png)
<img width="419" alt="error" src="https://user-images.githubusercontent.com/59681912/72049585-2d36cb80-32fa-11ea-8cc3-95e81778c89a.png">

**Comment by pkhungurn** [comment]
Please refer to https://github.com/pkhungurn/talking-head-anime-demo/issues/1
